// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Attachment struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Url       string    `json:"url"`
	CourseID  string    `json:"course_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Chapter struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	VideoUrl    string    `json:"video_url"`
	Position    int64     `json:"position"`
	IsPublished bool      `json:"is_published"`
	IsFree      bool      `json:"is_free"`
	CourseID    string    `json:"course_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Course struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	Price       int64     `json:"price"`
	IsPublished bool      `json:"is_published"`
	CategoryID  string    `json:"category_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Mux struct {
	ID         string         `json:"id"`
	AssetID    string         `json:"asset_id"`
	PlaybackID sql.NullString `json:"playback_id"`
	ChapterID  string         `json:"chapter_id"`
}

type Purchase struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CourseID  string    `json:"course_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StripeCustomer struct {
	ID               string    `json:"id"`
	UserID           string    `json:"user_id"`
	StripeCustomerID string    `json:"stripe_customer_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	ImageUrl          string    `json:"image_url"`
	BannerUrl         string    `json:"banner_url"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type UserProgress struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	ChapterID   string    `json:"chapter_id"`
	IsCompleted bool      `json:"is_completed"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UsersWithCourse struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	ImageUrl          string    `json:"image_url"`
	BannerUrl         string    `json:"banner_url"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	Courses           string    `json:"courses"`
}
