// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id string) error
	DeleteCourse(ctx context.Context, id string) error
	GetCategory(ctx context.Context, id string) (Category, error)
	GetCourse(ctx context.Context, arg GetCourseParams) (GetCourseRow, error)
	GetUserWithCourses(ctx context.Context, username string) (UsersWithCourse, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error)
	ListCoursesByUserID(ctx context.Context, arg ListCoursesByUserIDParams) ([]ListCoursesByUserIDRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
}

var _ Querier = (*Queries)(nil)
